# Generated by Django 2.0.3 on 2018-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180409_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('work', models.CharField(max_length=200)),
            ],
        ),
    ]
