# Generated by Django 2.0.3 on 2018-04-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_maids'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Maids',
        ),
    ]
