# Generated by Django 2.0.3 on 2018-04-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20180410_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='area',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
