# Generated by Django 2.0.3 on 2018-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_accessrecord_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputuser',
            name='field',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='inputuser',
            name='area',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='inputuser',
            name='email',
            field=models.EmailField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='inputuser',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
